### ISSUE TITLE
Use adaptive.js from AdaptiveMe/adaptive-arp-javascript repo

### ISSUE THREAD

**Issue by carloslozano** [AdaptiveMe/generator-adaptiveme#24]
Please source new adaptive.\* files from https://github.com/AdaptiveMe/adaptive-arp-javascript.

Please also note the new tagging convention without v (previously v2.2.x, now 2.2.x)

**Comment by ferranvila** [comment]
The generator loads the Adaptive Javascript API from the **Bower Definitions**. The build process has to update this definition after generates a new API: https://github.com/AdaptiveMe/adaptive-arp-javascript/issues/3

The npm-generator is not versioned with the ARP API, works by itself.
