### ISSUE TITLE
Travis-CI Deploy > 27 minutes to deploy npm

### ISSUE THREAD

**Issue by carloslozano** [AdaptiveMe/generator-adaptiveme#27]

**Comment by carloslozano** [comment]
Payload size: **4MB** (uploaded)
Payload download: https://registry.npmjs.org/generator-adaptiveme/-/generator-adaptiveme-1.0.5.tgz

Payload+dependencies: **40MB** (_36MB_ dependencies, _4MB_ generator, downloaded during install)

The latency is probably the cause of the slow build but it's worth revising.

**Comment by ferranvila** [comment]
![xfiles](https://cloud.githubusercontent.com/assets/8384895/7087067/bff66f1e-df87-11e4-8765-880d4fafb21b.jpg)
