### ISSUE TITLE
Typescript argument as "false" being ignored

### ISSUE THREAD

**Issue by Panthro** [AdaptiveMe/generator-adaptiveme#45]
Steps to reproduce:
1. Install generator
2. execute the following command
 `yo adaptiveme generator-no-ts latest false "Initializr Bootstrap" --skip-install --skip-server`

Note the 3rd parameter is **false**

Check that a file in the path `src/js/main.ts` exists

**Comment by Panthro** [comment]
In the line https://github.com/AdaptiveMe/generator-adaptiveme/blob/master/generators/app/index.js#L183

The attribution of the arg3 is passed without comparing to a boolean object, so the param_typescript is not `false` is a `"false"`

In line https://github.com/AdaptiveMe/generator-adaptiveme/blob/master/generators/app/index.js#L284
The value is used in a condition and it evaluates as  `true` because it's not `undefined`

**Comment by ferranvila** [comment]
Fixed. @Panthro Thanks for the comment!!

Now you can run:

```
yo adaptiveme test latest false "Initializr Boostrap" "ios,android" --skip-install --skip-server
```
