### ISSUE TITLE
Global shouldnt be the default installation mode when installing npm modules

### ISSUE THREAD

**Issue by Panthro** [AdaptiveMe/generator-adaptiveme#51]
Any tool that can be used for scripting shouldn't attempt to perform Administrator/Root level operations by default.

This creates two bad situations:
1. When the tool is used inside another tool (as in the @AdaptiveMe/adaptiveme-ide-platform ) the installation will be paused until the user provides the password in mac and linux, and on windows will fail.
2. When the user does not have the proper admin rights he won't be able to execute the script thus not able to install & use the tool (we all know this might be the case in big companies)

I know this causes the issue that we have to download nibble every time a new project is created, but I don't executing root/admin operations by default should be the solution.

**Comment by ferranvila** [comment]
Solved.
