### ISSUE TITLE
Error running npm-install right after project creation when project name has hyphens

### ISSUE THREAD

**Issue by Panthro** [AdaptiveMe/generator-adaptiveme#61]
Steps to reproduce
1. Execute `yo adaptiveme adaptive-sample-app2 latest false none android,ios --ios-version 8.1 --android-version 5.0 --skip-install --skip-cache`
2. Execute `npm install`

When the project name containns the `-`char the package.json generated is replacing it for ` ` (spaces) which breaks npm install with the following error:

```
npm ERR! install Couldn't read dependencies
npm ERR! Darwin 14.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.4
npm ERR! npm  v2.13.2

npm ERR! Invalid name: "adaptive sample app2"
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
```

The piece of package.json generated:

```
{
  "name": "adaptive sample app2",
  "title": "adaptive sample app2",
  "version": "0.0.1",
  "description": "Description for adaptive sample app2"
 }
```

**Comment by ferranvila** [comment]
Fixed. With c973a524751146854f11683c299cd0d7b4efecb0. The version uploaded was incorrect due to automatic publishing on npm generator.
