### ISSUE TITLE
Android version is wrong after generator

### ISSUE THREAD

**Issue by Panthro** [AdaptiveMe/generator-adaptiveme#63]
1. `yo adaptiveme adaptivesampleapp latest false none android,ios --ios-version 8.1 --android-version 5.0 --skip-install --skip-cache`
2. check `adaptive.yml` and android version is `5` and not `5.0`as passed

**Comment by ferranvila** [comment]
Mitigated the error... We define a new version of android for 5.0 with the tag 5
